repos:
  - repo: local
    hooks:
      - id: lint
        name: task lint
        entry: task lint
        language: system
        pass_filenames: false
        always_run: true
      - id: analyze
        name: task analyze
        entry: task analyze
        language: system
        pass_filenames: false
        always_run: true
      - id: test
        name: task test
        entry: task test
        language: system
        pass_filenames: false
        always_run: true
