version: '3'

tasks:
  docs:serve:
    desc: Serve live updated docs
    cmds:
      - poetry run mkdocs serve
  jupyter:
    desc: Run jupyterlab notebooks from poetry env
    cmds:
      - poetry run jupyter lab
  benchmark:
    desc: Run benchmarks
    cmds:
      - poetry run richbench benchmarks/
  format:
    desc: Format all code with black and isort
    cmds:
      - poetry run black .
      - poetry run ruff --fix .
  lint:
    desc: Lint code with flake8, isort and black
    cmds:
      - poetry run black --check .
      - poetry run ruff .
  analyze:
    desc: Analyze code with mypy, xenon and bandit
    cmds:
      - poetry run mypy src tests examples
      - poetry run xenon -b B -m B -a A src
      - poetry run bandit -c pyproject.toml -r .
  test:
    desc: Run all tests
    cmds:
      - poetry run pytest
  full-check:
    desc: run linting and testing
    cmds:
      - task: lint
      - task: analyze
      - task: test
